package output

import (
	"fmt"
	"strings"
	"time"
)

type HTMLReport struct {
	Title     string
	Target    string
	StartedAt time.Time
	Sections  []HTMLSection
}

type HTMLSection struct {
	Title   string
	Content string
}

func NewHTMLReport(title, target string) *HTMLReport {
	return &HTMLReport{
		Title:     title,
		Target:    target,
		StartedAt: time.Now(),
	}
}

func (r *HTMLReport) AddSection(title, content string) {
	r.Sections = append(r.Sections, HTMLSection{Title: title, Content: content})
}

func (r *HTMLReport) Render() string {
	var b strings.Builder

	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	b.WriteString("<meta charset=\"UTF-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	b.WriteString(fmt.Sprintf("<title>%s — %s</title>\n", r.Title, r.Target))
	b.WriteString(`<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Inter','Segoe UI',system-ui,sans-serif;background:#0f172a;color:#e2e8f0;line-height:1.6}
.container{max-width:1200px;margin:0 auto;padding:20px}
header{background:linear-gradient(135deg,#1e293b,#0f172a);border:1px solid #334155;border-radius:12px;padding:32px;margin-bottom:24px}
header h1{font-size:28px;font-weight:700;margin-bottom:4px}
header .subtitle{color:#94a3b8;font-size:14px}
header .meta{display:flex;gap:24px;margin-top:16px}
header .meta span{display:flex;align-items:center;gap:6px;font-size:13px;color:#cbd5e1;background:#1e293b;padding:6px 12px;border-radius:8px;border:1px solid #334155}
section{background:#1e293b;border:1px solid #334155;border-radius:12px;margin-bottom:16px;overflow:hidden}
section h2{background:#334155;padding:16px 20px;font-size:16px;font-weight:600;border-bottom:1px solid #475569}
section .content{padding:20px}
table{width:100%;border-collapse:collapse;font-size:13px}
th{text-align:left;padding:10px 12px;background:#334155;color:#94a3b8;font-weight:600;border-bottom:1px solid #475569}
td{padding:10px 12px;border-bottom:1px solid #334155}
tr:hover{background:#33415580}
.status-ok{color:#22c55e} .status-warn{color:#eab308} .status-err{color:#ef4444}
pre{background:#0f172a;padding:16px;border-radius:8px;overflow-x:auto;font-size:12px;line-height:1.5;color:#94a3b8;border:1px solid #334155}
.tag{display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:500}
.tag-ok{background:#166534;color:#86efac} .tag-err{background:#991b1b;color:#fca5a5} .tag-warn{background:#854d0e;color:#fde047} .tag-info{background:#1e3a5f;color:#93c5fd}
footer{text-align:center;padding:24px;color:#64748b;font-size:12px;border-top:1px solid #1e293b}
</style>
</head>
<body>
`)
	b.WriteString("<div class=\"container\">\n")
	b.WriteString(fmt.Sprintf("<header>\n<h1>%s</h1>\n", r.Title))
	b.WriteString(fmt.Sprintf("<p class=\"subtitle\">Target: %s</p>\n", r.Target))
	b.WriteString("<div class=\"meta\">")
	b.WriteString(fmt.Sprintf("<span>Start: %s</span>", r.StartedAt.Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("<span>Sections: %d</span>", len(r.Sections)))
	b.WriteString("<span>Generated by oxrecon</span>")
	b.WriteString("</div>\n</header>\n")

	for _, s := range r.Sections {
		b.WriteString(fmt.Sprintf("<section>\n<h2>%s</h2>\n", s.Title))
		b.WriteString("<div class=\"content\">\n")
		if s.Title == "Raw" || strings.Contains(s.Title, "Code") || strings.Contains(s.Title, "Raw") {
			b.WriteString(fmt.Sprintf("<pre>%s</pre>\n", escapeHTML(s.Content)))
		} else {
			b.WriteString("<pre>" + s.Content + "</pre>\n")
		}
		b.WriteString("</div>\n</section>\n")
	}

	b.WriteString(fmt.Sprintf("<footer>oxrecon v1.0.0 — %s</footer>\n", r.StartedAt.Format("2006")))
	b.WriteString("</div>\n</body>\n</html>")

	return b.String()
}

func escapeHTML(s string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		"\"", "&quot;",
	)
	return replacer.Replace(s)
}
